### ISSUE TITLE
Main character texture for prototype

### ISSUE THREAD

**Issue by D4ndellion** [dali99/F-Science#1]
So no need to pour your heart and soul into it

**Comment by oskarskaane** [comment]
Ere pixelart?

**Comment by D4ndellion** [comment]
mfw we havent even discussed artstyle

**Comment by D4ndellion** [comment]
I really don't want it to be like, 16bit or whatever
but like, Fez's artstyle is good

Even better maybe Cave Story+. Which is pretty gorgeus
